name: ram_demo_app
description: "This is Rick and Morty demo app for portfolio"
publish_to: 'none' 

version: 1.0.2

environment:
  sdk: ^3.10.9
  flutter: "^3.38.10"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # UI Tools
  flutter_svg: ^2.2.4
  toastification: ^3.0.3
  cached_network_image: ^3.4.1

  # Dependency Injection
  get_it: ^9.2.1
  injectable: ^2.7.1+4

  # Localization
  slang_flutter: 4.12.1
  flutter_localizations:
    sdk: flutter

  # GraphQL
  graphql: ^5.2.4
  dio: ^5.9.2
  gql_dio_link: ^2.0.0

  # Storage
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^10.0.0

  # Logger
  talker: ^5.1.16
  talker_dio_logger: ^5.1.16
  talker_bloc_logger: ^5.1.16

  # Router
  auto_route: ^11.1.0

  # Assets
  flutter_gen: ^5.13.0+1

  # State Management
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  rxdart: ^0.28.0

  # Logic Tools
  freezed: ^3.2.5
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0
  gql: ^1.0.1
  intl: ^0.20.2
  html: ^0.15.6
  flutter_cache_manager: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  mockito: ^5.4.5
  build_runner: ^2.13.1
  injectable_generator: ^2.12.1
  slang_build_runner: ^4.12.1
  graphql_codegen: ^3.0.1
  auto_route_generator: ^10.4.0
  flutter_gen_runner: ^5.13.0+1
  json_serializable: ^6.13.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/l10n/
    - assets/fonts/
    - assets/env/

  fonts:
    - family: Golos
      fonts:
        - asset: assets/fonts/golos/GolosText-Black.ttf
          weight: 900
        - asset: assets/fonts/golos/GolosText-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/golos/GolosText-Bold.ttf
          weight: 700
        - asset: assets/fonts/golos/GolosText-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/golos/GolosText-Medium.ttf
          weight: 500
        - asset: assets/fonts/golos/GolosText-Regular.ttf
          weight: 400
