fragment CharacterFragment on Character{
    id
    name
    status
    species
    type
    gender
    origin
    location
    image
    episode
    created
}

fragment InfoFragment on Info{
    count
    pages
    next
    prev
}

fragment LocationFragment on Location{
    id
    name
    type
    dimension
    residents
    created
}

  id: ID

  """The name of the character."""
  name: String

  """The status of the character ('Alive', 'Dead' or 'unknown')."""
  status: String

  """The species of the character."""
  species: String

  """The type or subspecies of the character."""
  type: String

  """
  The gender of the character ('Female', 'Male', 'Genderless' or 'unknown').
  """
  gender: String

  """The character's origin location"""
  origin: Location

  """The character's last known location"""
  location: Location

  """
  Link to the character's image.
  All images are 300x300px and most are medium shots or portraits since they are intended to be used as avatars.
  """
  image: String

  """Episodes in which this character appeared."""
  episode: [Episode]!

  """Time at which the character was created in the database."""
  created: String